language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
install: npm install
script: npm run coverage
after_script: npm run coveralls
branches:
  only:
    - master
notifications:
  email:
    on_success: never
    on_failure: change
